config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts do
  	resources :comments
  end
  root "posts#index"

  get '/about', to: 'pages#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post

  validates :name, presence: true
	validates :body, presence: true
end

app/models/post.rb
class Post < ApplicationRecord

	has_many :comments, dependent: :destroy

	validates :title, presence: true, length: { minimum: 5 }
	validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!
	
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment].permit(:name, :body))

		redirect_to post_path(@post)
	end

	def destroy
		@post = Post.find(params[:post_id]) 
		@comment = @post.comments.find(params[:id]) 
		@comment.destroy

		redirect_to post_path(@post)

	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def about
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@posts = Post.all.order('created_at DESC')
	end

	def new
		@post = Post.new
	end

'''save the posts '''
	def create
		@post = Post.new(post_params)

		if @post.save 
			redirect_to @post
		else
			render 'new'
		end
	end

	def show
		@post = Post.find(params[:id])
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])

		if @post.update(params[:post].permit(:title, :body))
			redirect_to @post
		else
			render 'edit'
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		
		redirect_to root_path
	end


	private

		def post_params
			params.require(:post).permit(:title, :body)
		end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
	

<!-- show comments -->
	<div class="comment_content">
		<p class="comment_name"><strong><%= comment.name %></strong></p>
		<p class="comment_body"><%= comment.body %></p>
		<p class="comment_title"><%= time_ago_in_words(comment.created_at)%> ago</p>
	</div>
	
	<% if user_signed_in? %>
		<p><%= link_to 'Delete', [comment.post, comment], method: :delete, class: "button", data: {confirm: 'Are you sure?'}%></p>
	<% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
	
	<% #if user_signed_in? %>

		<p>
			<%= f.label :name %><br>
			<%= f.text_field :name %>
		</p>

		<p>
			<%= f.label :body %><br>
			<%= f.text_area :body %><br>
		</p>
		<br>
		<p>
			<%= f.submit %>
		</p>
	<% # end %>


<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tumblr</title>
    

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <%= stylesheet_link_tag		 'application', 'https://fonts.googleapis.com/css?family=Raleway'	 %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= csrf_meta_tags %>
  </head>

  <body>

  	<div id="sidebar">
  		<ul>
  			<li class="category"><%= link_to "Tumblr", root_path %></li>
  			<li><%= link_to "Posts", root_path %></li>
  			<li><%= link_to "About", about_path %></li>
  		</ul>

      <% if !user_signed_in? %>
  		  <p class="sign_in"><%= link_to "User Login", new_user_session_path %></p>
      <% end %>
    </div>

  	<div id="main_content">
  		
  		<div id="header">

        <% if current_page?(root_path) %>
          <p>Post Feed</p>
        <% elsif current_page?(about_path) %>
          <p>My Site</p>
        <% else %>
          <%= link_to "Back to Post Feed", root_path %>
        <% end %>
          
  		  <% if user_signed_in? %>
          <div class="buttons">
    				<button class="button"><%= link_to "Make Post", new_post_path %></button>
    				<button class="button"><%= link_to "Log Out", destroy_user_session_path, method: :delete %></button>
  			 </div> <!-- buttons -->
        <% end %>
  		</div> <!-- header -->

  		<% flash.each do |name, msg| %>
  			<%= content_tag(:div, msg, class: "alert") %>
  		<% end %>
  		<%= yield %>
  	</div>

   
  </body>
</html>

app/views/pages/about.html.erb
<div id="page_wrapper">
	<div id="profile_image">
		<%= image_tag "profile.jpeg" %>
	</div>

	<div id="content">
		<h1>It's Bruna Carlota</h1>
		<p>Mixtape kinfolk four dollar toast, keytar adaptogen cardigan jianbing taxidermy enamel pin irony bushwick gastropub cronut. YOLO keytar skateboard taxidermy, pop-up twee everyday carry scenester. Salvia subway tile distillery tote bag, messenger bag tilde narwhal edison bulb. Whatever celiac shoreditch green juice jean shorts. Snackwave tilde kinfolk flannel, taxidermy raclette pickled gochujang williamsburg pour-over freegan air plant 3 wolf moon listicle tbh. Meggings ethical 8-bit mixtape woke, fashion axe listicle church-key knausgaard tofu paleo unicorn single-origin coffee migas. Meh fanny pack disrupt pop-up la croix tbh.</p>
	</div>
</div>

app/views/posts/_form.html.erb
	<%= form_for @post do |f| %>

		<% if @post.errors.any? %>
			<div id="errors">
				<h2><%= pluralize(@post.errors.count, "error") %> stopped this post from saving</h2>
				<ul>
					<% @post.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
					<% end %>
				</ul>
			</div>
		<% end %>

		<p>
			<%= f.label :title %><br>
			<%= f.text_field :title %><br>
		</p>

		<p>
			<%= f.label :body %><br>
			<%= f.text_area :body %><br>
		</p>

		<p>
			<%= f.submit %>
		</p>

	<% end %>

app/views/posts/edit.html.erb
<div id="page_wrapper">

	<h1>Fix Post</h1>

	<%= render 'form' %>

</div>

app/views/posts/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<% @posts.each do |post| %>
		<div class="post_wrapper">
			<h2 class="title"><%= link_to post.title, post %></h2>
			<p class="body"><%= truncate(post.body, length:100) %></p>
			<p class="date"><%= time_ago_in_words(post.created_at) %> ago</p>
		</div>
	<% end %>
</body>
</html>

app/views/posts/new.html.erb
<div id="page_wrapper">

	<h1>Make something</h1>

	<%= render 'form' %>

</div>

app/views/posts/show.html.erb
<div id="post_content">

	<h1 class="title">
		<%= @post.title %>
	</h1>

	<p class="date">
		Submited <%= time_ago_in_words(@post.created_at) %> ago

		<% if user_signed_in? %> 
			|
		
			<%= link_to 'Edit', edit_post_path(@post) %> | 
			<%= link_to 'Delete', post_path(@post), method: :delete, data: {confirm: 'Are you sure?'} %>
		<% end %>

	</p>

	<p class="body">
		<%= @post.body %>
	</p>

	<div id="comments">
		<h2><%= @post.comments.count %> Comments</h2>
		<%= render @post.comments %>
		<h3>Join Discussion: </h3>
		<%= render "comments/form" %>
	</div>

</div>